### ISSUE TITLE
Question about the SubscriberProvider

### ISSUE THREAD

**Issue by jeroendk** [welpdev/mailchimp-bundle#13]
Hi!

I am trying to make the the list config manageable, so i store the list id etc. in the Database.
It is all working now but i had to overwrite a lot of classes. 

There's one thing I wondered, why is there a separate subscriber provider per list ? As a said my list are managed in the database so i can't create a new provider for each list. Isn't it handy to use one subscriber provider that gets the list as parameter when getSubscribers is called ? 

`public function getSubscribers(SubscriberList $list)`

**Comment by Nightbr** [comment]
Hello,

it depends, in my projects, I can have several provider:
* FosUserProvider to load my subscribers from my User Entity
* CSVProvider because we need to import subscribers from CSV file
* ...

If you try to get List manageable (create new functionnalities such as CRUD on List endpoint), I think you can fork this bundle and implement directly a ListManager which use https://github.com/welpdev/mailchimp-bundle/blob/master/src/Subscriber/ListRepository.php and expose it as a service with your needed method.

**Comment by jeroendk** [comment]
Thanks for the quick reply.

By making the list manageable I mean i want to have the parameters now defined in the config to be manageable. I dont need to edit the actual list in Mailchimp. I already extended the SubscriberList class and added Doctrine mapping. So i can expose this entity to the CMS and add new lists on the go. These lists are by then already created in Mailchimp

I have a 'problem' with the following method:

    public function synchronize(SubscriberList $list)
    {   

        $listData = $this->listRepository->findById($list->getListId());

        // get Subscribers from the provider
        $subscribers = $list->getProvider()->getSubscribers();

        // unsubscribe difference
        $this->unsubscribeDifference($list->getListId(), $subscribers);
        // subscribe the rest
        return $this->batchSubscribe($list->getListId(), $subscribers);
    }

`$subscribers = $list->getProvider()->getSubscribers();`
How does my "UserProvider" know which users to fetch when I use the same entity for multiple list with for example an extra column for the list.

**Comment by Nightbr** [comment]
Can you put some more code in order to understand the context. 

What I understand:
1. You have an Entity MailchimpList which contains ListId, and other data (such as subscribers fields)
2. You want to synchronize by using the Bundle method Synchronize

I think you can achieve this by building a Dynamic Provider.

``` php
<?php
namespace Welp\MailchimpBundle\Provider;

use Welp\MailchimpBundle\Provider\ProviderInterface;
use Welp\MailchimpBundle\Subscriber\Subscriber;

class MyDynamicProvider implements ProviderInterface
{

    protected $list;
    public function __construct(MyListEntity $list)
    {
        $this->list = $list;
    }
    /**
     * {@inheritdoc}
     */
    public function getSubscribers()
    {
        $users = $this->list->findUsers();
        $params = $this->list->getParams();
       
        $subscribers = array_map(function (User $user) {
            $subscriber = new Subscriber($user->getEmail(), 
            array_map(function ($param) {
            return [$param => $user->{'get'.$params}()];
            },$params);
            return $subscriber;
        }, $users);
        return $subscribers;
    }
}
```

I have not tested this but I think it can work.

Try it and let me know!

**Comment by jeroendk** [comment]
Well that would be ideal but i have to inject the list then right ? the SynchronizeSubscribersCommand for example retrieves the service from the container so how does it switch between lists when syncing all at the same time ?

**Comment by Nightbr** [comment]
yep.... I haven't face these use cases in fact ^^ Add to that, if you have a lot of list and subscribers you need to implement a batch system for performance issue... 

If you have a solution, you can create a PR and we will review it together to add the functionality.

**Comment by jeroendk** [comment]
Alright I will work on it when i have some time! 

Thanks.
