### ISSUE TITLE
Question: Is the ListSynchronizer working with list of more than 200K subscribers ?

### ISSUE THREAD

**Issue by mpoiriert** [welpdev/mailchimp-bundle#22]
We have a big subscriber base and we need to sync it.

I am just using your bundle (I move everything from Laraval to Symfony) and I am wondering if it will work with list that big ?

**Comment by Nightbr** [comment]
Hey,

**DISCLAIMER:**

we are an independant OpenSource project and we do not work with or for MailChimp. We cannot guarantee anything here. Make our own choice and be responsible for it. More information in our [LICENCE](https://github.com/welpdev/mailchimp-bundle/blob/master/LICENSE.md).

Now we can talk tech :ok_hand: Yes this bundle can handle more than 200k subscribers. Our command to synchronize Subscribers use Batch requests so in theory it will synchronize your 200k subscribers but it will take some times. 

Related documentation: <https://welpdev.github.io/mailchimp-bundle/usage/#full-synchronization-with-command>

If you find a bug, feel free to open another issue, create PR to fix it, ...

I will close this issue because technically it's not an issue.

/close

**Comment by mpoiriert** [comment]
Thanks for the quick reply.

I read the code (pretty much all of it) and the sync functionality is not appropriate for what we want to do (master reference logic is more complex than just using our database as the reference). I also note a few improvement that can be done and one error.

I don't know if you are still using/developing this bundle but would you want me to give you my insight here or by any other mean ?

**Comment by Nightbr** [comment]
Hey, you can fork the repo and create your fixes and improvment. Next you create a pull Request and we discuss on the PR. If your modification sounds good I will merge your PR and tag a new release :+1:
