### ISSUE TITLE
Impossible to Subscribe with status "pending"

### ISSUE THREAD

**Issue by raphaelvigee** [welpdev/mailchimp-bundle#9]
Hello !

Very good work creating this bundle!

Small issue: how can i subscribe a user with the "pending" status as it is forced https://github.com/welpdev/mailchimp-bundle/blob/master/src/Subscriber/ListRepository.php#L74 ?

Thx

**Comment by Nightbr** [comment]
Hey,

thanks you for your interest in this bundle.

Here is 3 solutions:

1. You can use the MailChimp API service and create your specific request:

``` PHP
    /**
     * Pending a Subscriber to a list
     * @param string $listId
     * @param Subscriber $subscriber
     * @return array
     */
    public function pending($listId, Subscriber $subscriber)
    {
        $MailChimp = $this->container->get('welp_mailchimp.mailchimp_master');
        $subscriberHash = $MailChimp->subscriberHash($subscriber->getEmail());
        $result = $MailChimp->put("lists/$listId/members/$subscriberHash",
            array_merge(
                $subscriber->formatMailChimp(),
                ['status' => 'pending']
            )
        );

        if (!$MailChimp->success()) {
            throw new \RuntimeException($MailChimp->getLastError());
        }

        return $result;
    }
```

You can create your own service and inject `welp_mailchimp.mailchimp_master` service or directly use the function into your controller.

[See the documentation](https://welpdev.github.io/mailchimp-bundle/usage/#retrieve-mailchimp-object-to-make-custom-mailchimp-api-v3-requests)

2. You can create a PR with the feature you want, and we will review it together and merge it into the main project

3. You can wait I implement this feature. I think I can find some time next week in order to add a generic function `addSubscriberWithStatus` and create function alias for all status:

* subscribed: `public function subscribe($listId, Subscriber $subscriber)`
* unsubscribed: `public function subscribe($listId, Subscriber $subscriber)`
* cleaned: `public function clean($listId, Subscriber $subscriber)`
* pending: `public function pending($listId, Subscriber $subscriber)`
* transactional: `public function transactional($listId, Subscriber $subscriber)`

And create a event and listener for these functions in order to use them like subscribe and unsubscribe.

Hope I have answer your question !

**Comment by raphaelvigee** [comment]
The PR I just made is in my opinion the easiest, non backward-compatibility-breaking method

**Comment by Nightbr** [comment]
Hey thanks for your PR but I think that you have done is a bit a hack than a real solution to this problem... And I really want to keep this bundle simple and clear as possible.

So I will closed your PR, thanks for your comprehension.

Also, I have look at my last commit https://github.com/welpdev/mailchimp-bundle/commit/c38c30f350d0d35d4e4c951024402591b48b1835 and tell me if this solution can resolve your issue. I have also update the documentation on master branch https://github.com/welpdev/mailchimp-bundle/blob/master/src/Resources/doc/usage.md#unit-synchronization-with-events

Let me know if it needs modification. If not, I will make a release.

Thanks for your contribution

**Comment by raphaelvigee** [comment]
Hey !

I don't see my solution as a hack but rather as a quick solution/fix for the problem.

But your solution is defenitely cleaner ! Ok for release :+1:

**Comment by Nightbr** [comment]
Released! https://github.com/welpdev/mailchimp-bundle/releases/tag/1.0.10

Thanks for your contribution :+1:
